@echo off
setlocal

set FXC=
for /f "delims=" %%i in ('dir /s /b "C:\Program Files (x86)\Windows Kits\10\bin\*\x64\fxc.exe" 2^>nul') do set FXC=%%i

if "%FXC%"=="" (
    echo ERROR: fxc.exe not found. Install Windows SDK.
    exit /b 1
)

echo Using: %FXC%

"%FXC%" /T vs_5_0 /E main /Vn g_imgui_vs /Fh imgui_vs.inc imgui_vs.hlsl
if errorlevel 1 exit /b 1

"%FXC%" /T ps_5_0 /E main /Vn g_imgui_ps /Fh imgui_ps.inc imgui_ps.hlsl
if errorlevel 1 exit /b 1

(
echo #pragma once
echo.
echo // Auto-generated by compile_shaders.bat — do not edit
echo.
type imgui_vs.inc
echo.
type imgui_ps.inc
) > imgui_dx12_shaders.h

del imgui_vs.inc imgui_ps.inc 2>nul
echo Done: imgui_dx12_shaders.h generated
